<?php

declare(strict_types = 1);

namespace Resrap\Examples\Jsx;

use Resrap\Component\Parser\Parser;
use Resrap\Component\Scanner\Scanner;
use Resrap\Examples\Jsx\Ast\ConstDeclaration;
use Resrap\Examples\Jsx\Ast\Identifier;
use Resrap\Examples\Jsx\Ast\Interpolation;
use Resrap\Examples\Jsx\Ast\JsxAttribute;
use Resrap\Examples\Jsx\Ast\JsxElement;
use Resrap\Examples\Jsx\Ast\NumberLiteral;
use Resrap\Examples\Jsx\Ast\Program;
use Resrap\Examples\Jsx\Ast\TextNode;

/**
 * This file was generated by the grammar compiler.
 * Do not edit it manually.
 */
final class JsxParser
{
    private const array RULES = [
        0 =>
            [
                0 => 'program',
                1 =>
                    [
                        0 => 'statements',
                    ],
            ],
        1 =>
            [
                0 => 'statements',
                1 =>
                    [
                        0 => 'statement',
                        1 => 'statements',
                    ],
            ],
        2 =>
            [
                0 => 'statements',
                1 =>
                    [
                    ],
            ],
        3 =>
            [
                0 => 'statement',
                1 =>
                    [
                        0 => 'constDeclaration',
                    ],
            ],
        4 =>
            [
                0 => 'statement',
                1 =>
                    [
                        0 => 'expression',
                    ],
            ],
        5 =>
            [
                0 => 'constDeclaration',
                1 =>
                    [
                        0 => 'CONST',
                        1 => 'IDENTIFIER',
                        2 => 'EQUALS',
                        3 => 'expression',
                        4 => 'SEMICOLON',
                    ],
            ],
        6 =>
            [
                0 => 'expression',
                1 =>
                    [
                        0 => 'jsxElement',
                    ],
            ],
        7 =>
            [
                0 => 'expression',
                1 =>
                    [
                        0 => 'identifier',
                    ],
            ],
        8 =>
            [
                0 => 'expression',
                1 =>
                    [
                        0 => 'number',
                    ],
            ],
        9 =>
            [
                0 => 'jsxElement',
                1 =>
                    [
                        0 => 'jsxSelfClosing',
                    ],
            ],
        10 =>
            [
                0 => 'jsxElement',
                1 =>
                    [
                        0 => 'jsxWithChildren',
                    ],
            ],
        11 =>
            [
                0 => 'identifier',
                1 =>
                    [
                        0 => 'IDENTIFIER',
                    ],
            ],
        12 =>
            [
                0 => 'number',
                1 =>
                    [
                        0 => 'NUMBER',
                    ],
            ],
        13 =>
            [
                0 => 'jsxSelfClosing',
                1 =>
                    [
                        0 => 'JSX_TAG_OPEN',
                        1 => 'IDENTIFIER',
                        2 => 'jsxAttributes',
                        3 => 'JSX_TAG_SELF_CLOSE',
                    ],
            ],
        14 =>
            [
                0 => 'jsxWithChildren',
                1 =>
                    [
                        0 => 'JSX_TAG_OPEN',
                        1 => 'IDENTIFIER',
                        2 => 'jsxAttributes',
                        3 => 'JSX_TAG_CLOSE',
                        4 => 'jsxChildren',
                        5 => 'JSX_TAG_END_OPEN',
                        6 => 'IDENTIFIER',
                        7 => 'JSX_TAG_CLOSE',
                    ],
            ],
        15 =>
            [
                0 => 'jsxAttributes',
                1 =>
                    [
                        0 => 'jsxAttribute',
                        1 => 'jsxAttributes',
                    ],
            ],
        16 =>
            [
                0 => 'jsxAttributes',
                1 =>
                    [
                    ],
            ],
        17 =>
            [
                0 => 'jsxChildren',
                1 =>
                    [
                        0 => 'jsxChild',
                        1 => 'jsxChildren',
                    ],
            ],
        18 =>
            [
                0 => 'jsxChildren',
                1 =>
                    [
                    ],
            ],
        19 =>
            [
                0 => 'jsxAttribute',
                1 =>
                    [
                        0 => 'JSX_ATTR_NAME',
                        1 => 'EQUALS',
                        2 => 'STRING',
                    ],
            ],
        20 =>
            [
                0 => 'jsxAttribute',
                1 =>
                    [
                        0 => 'JSX_ATTR_NAME',
                        1 => 'EQUALS',
                        2 => 'BRACE_OPEN',
                        3 => 'expression',
                        4 => 'BRACE_CLOSE',
                    ],
            ],
        21 =>
            [
                0 => 'jsxChild',
                1 =>
                    [
                        0 => 'jsxElement',
                    ],
            ],
        22 =>
            [
                0 => 'jsxChild',
                1 =>
                    [
                        0 => 'JSX_TEXT',
                    ],
            ],
        23 =>
            [
                0 => 'jsxChild',
                1 =>
                    [
                        0 => 'BRACE_OPEN',
                        1 => 'expression',
                        2 => 'BRACE_CLOSE',
                    ],
            ],
    ];
    private const array ACTIONS = [
        0 =>
            [
                '$' =>
                    [
                        0 => 1,
                        1 => 2,
                    ],
                'CONST' =>
                    [
                        0 => 0,
                        1 => 5,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 11,
                    ],
                'NUMBER' =>
                    [
                        0 => 0,
                        1 => 12,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 0,
                        1 => 13,
                    ],
            ],
        1 =>
            [
                '$' =>
                    [
                        0 => 2,
                        1 => 0,
                    ],
            ],
        2 =>
            [
                '$' =>
                    [
                        0 => 1,
                        1 => 2,
                    ],
                'CONST' =>
                    [
                        0 => 0,
                        1 => 5,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 11,
                    ],
                'NUMBER' =>
                    [
                        0 => 0,
                        1 => 12,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 0,
                        1 => 13,
                    ],
            ],
        3 =>
            [
                'CONST' =>
                    [
                        0 => 1,
                        1 => 3,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 3,
                    ],
                'NUMBER' =>
                    [
                        0 => 1,
                        1 => 3,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 1,
                        1 => 3,
                    ],
                '$' =>
                    [
                        0 => 1,
                        1 => 3,
                    ],
            ],
        4 =>
            [
                'CONST' =>
                    [
                        0 => 1,
                        1 => 4,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 4,
                    ],
                'NUMBER' =>
                    [
                        0 => 1,
                        1 => 4,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 1,
                        1 => 4,
                    ],
                '$' =>
                    [
                        0 => 1,
                        1 => 4,
                    ],
            ],
        5 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 15,
                    ],
            ],
        6 =>
            [
                'CONST' =>
                    [
                        0 => 1,
                        1 => 6,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 6,
                    ],
                'NUMBER' =>
                    [
                        0 => 1,
                        1 => 6,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 1,
                        1 => 6,
                    ],
                '$' =>
                    [
                        0 => 1,
                        1 => 6,
                    ],
                'SEMICOLON' =>
                    [
                        0 => 1,
                        1 => 6,
                    ],
                'BRACE_CLOSE' =>
                    [
                        0 => 1,
                        1 => 6,
                    ],
            ],
        7 =>
            [
                'CONST' =>
                    [
                        0 => 1,
                        1 => 7,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 7,
                    ],
                'NUMBER' =>
                    [
                        0 => 1,
                        1 => 7,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 1,
                        1 => 7,
                    ],
                '$' =>
                    [
                        0 => 1,
                        1 => 7,
                    ],
                'SEMICOLON' =>
                    [
                        0 => 1,
                        1 => 7,
                    ],
                'BRACE_CLOSE' =>
                    [
                        0 => 1,
                        1 => 7,
                    ],
            ],
        8 =>
            [
                'CONST' =>
                    [
                        0 => 1,
                        1 => 8,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 8,
                    ],
                'NUMBER' =>
                    [
                        0 => 1,
                        1 => 8,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 1,
                        1 => 8,
                    ],
                '$' =>
                    [
                        0 => 1,
                        1 => 8,
                    ],
                'SEMICOLON' =>
                    [
                        0 => 1,
                        1 => 8,
                    ],
                'BRACE_CLOSE' =>
                    [
                        0 => 1,
                        1 => 8,
                    ],
            ],
        9 =>
            [
                'CONST' =>
                    [
                        0 => 1,
                        1 => 9,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 9,
                    ],
                'NUMBER' =>
                    [
                        0 => 1,
                        1 => 9,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 1,
                        1 => 9,
                    ],
                '$' =>
                    [
                        0 => 1,
                        1 => 9,
                    ],
                'SEMICOLON' =>
                    [
                        0 => 1,
                        1 => 9,
                    ],
                'JSX_TEXT' =>
                    [
                        0 => 1,
                        1 => 9,
                    ],
                'BRACE_OPEN' =>
                    [
                        0 => 1,
                        1 => 9,
                    ],
                'JSX_TAG_END_OPEN' =>
                    [
                        0 => 1,
                        1 => 9,
                    ],
                'BRACE_CLOSE' =>
                    [
                        0 => 1,
                        1 => 9,
                    ],
            ],
        10 =>
            [
                'CONST' =>
                    [
                        0 => 1,
                        1 => 10,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 10,
                    ],
                'NUMBER' =>
                    [
                        0 => 1,
                        1 => 10,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 1,
                        1 => 10,
                    ],
                '$' =>
                    [
                        0 => 1,
                        1 => 10,
                    ],
                'SEMICOLON' =>
                    [
                        0 => 1,
                        1 => 10,
                    ],
                'JSX_TEXT' =>
                    [
                        0 => 1,
                        1 => 10,
                    ],
                'BRACE_OPEN' =>
                    [
                        0 => 1,
                        1 => 10,
                    ],
                'JSX_TAG_END_OPEN' =>
                    [
                        0 => 1,
                        1 => 10,
                    ],
                'BRACE_CLOSE' =>
                    [
                        0 => 1,
                        1 => 10,
                    ],
            ],
        11 =>
            [
                'CONST' =>
                    [
                        0 => 1,
                        1 => 11,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 11,
                    ],
                'NUMBER' =>
                    [
                        0 => 1,
                        1 => 11,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 1,
                        1 => 11,
                    ],
                '$' =>
                    [
                        0 => 1,
                        1 => 11,
                    ],
                'SEMICOLON' =>
                    [
                        0 => 1,
                        1 => 11,
                    ],
                'BRACE_CLOSE' =>
                    [
                        0 => 1,
                        1 => 11,
                    ],
            ],
        12 =>
            [
                'CONST' =>
                    [
                        0 => 1,
                        1 => 12,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 12,
                    ],
                'NUMBER' =>
                    [
                        0 => 1,
                        1 => 12,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 1,
                        1 => 12,
                    ],
                '$' =>
                    [
                        0 => 1,
                        1 => 12,
                    ],
                'SEMICOLON' =>
                    [
                        0 => 1,
                        1 => 12,
                    ],
                'BRACE_CLOSE' =>
                    [
                        0 => 1,
                        1 => 12,
                    ],
            ],
        13 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 16,
                    ],
            ],
        14 =>
            [
                '$' =>
                    [
                        0 => 1,
                        1 => 1,
                    ],
            ],
        15 =>
            [
                'EQUALS' =>
                    [
                        0 => 0,
                        1 => 17,
                    ],
            ],
        16 =>
            [
                'JSX_TAG_SELF_CLOSE' =>
                    [
                        0 => 1,
                        1 => 16,
                    ],
                'JSX_TAG_CLOSE' =>
                    [
                        0 => 1,
                        1 => 16,
                    ],
                'JSX_ATTR_NAME' =>
                    [
                        0 => 0,
                        1 => 20,
                    ],
            ],
        17 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 11,
                    ],
                'NUMBER' =>
                    [
                        0 => 0,
                        1 => 12,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 0,
                        1 => 13,
                    ],
            ],
        18 =>
            [
                'JSX_TAG_SELF_CLOSE' =>
                    [
                        0 => 0,
                        1 => 22,
                    ],
                'JSX_TAG_CLOSE' =>
                    [
                        0 => 0,
                        1 => 23,
                    ],
            ],
        19 =>
            [
                'JSX_TAG_SELF_CLOSE' =>
                    [
                        0 => 1,
                        1 => 16,
                    ],
                'JSX_TAG_CLOSE' =>
                    [
                        0 => 1,
                        1 => 16,
                    ],
                'JSX_ATTR_NAME' =>
                    [
                        0 => 0,
                        1 => 20,
                    ],
            ],
        20 =>
            [
                'EQUALS' =>
                    [
                        0 => 0,
                        1 => 25,
                    ],
            ],
        21 =>
            [
                'SEMICOLON' =>
                    [
                        0 => 0,
                        1 => 26,
                    ],
            ],
        22 =>
            [
                'CONST' =>
                    [
                        0 => 1,
                        1 => 13,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 13,
                    ],
                'NUMBER' =>
                    [
                        0 => 1,
                        1 => 13,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 1,
                        1 => 13,
                    ],
                '$' =>
                    [
                        0 => 1,
                        1 => 13,
                    ],
                'SEMICOLON' =>
                    [
                        0 => 1,
                        1 => 13,
                    ],
                'JSX_TEXT' =>
                    [
                        0 => 1,
                        1 => 13,
                    ],
                'BRACE_OPEN' =>
                    [
                        0 => 1,
                        1 => 13,
                    ],
                'JSX_TAG_END_OPEN' =>
                    [
                        0 => 1,
                        1 => 13,
                    ],
                'BRACE_CLOSE' =>
                    [
                        0 => 1,
                        1 => 13,
                    ],
            ],
        23 =>
            [
                'JSX_TAG_END_OPEN' =>
                    [
                        0 => 1,
                        1 => 18,
                    ],
                'JSX_TEXT' =>
                    [
                        0 => 0,
                        1 => 30,
                    ],
                'BRACE_OPEN' =>
                    [
                        0 => 0,
                        1 => 31,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 0,
                        1 => 13,
                    ],
            ],
        24 =>
            [
                'JSX_TAG_SELF_CLOSE' =>
                    [
                        0 => 1,
                        1 => 15,
                    ],
                'JSX_TAG_CLOSE' =>
                    [
                        0 => 1,
                        1 => 15,
                    ],
            ],
        25 =>
            [
                'STRING' =>
                    [
                        0 => 0,
                        1 => 32,
                    ],
                'BRACE_OPEN' =>
                    [
                        0 => 0,
                        1 => 33,
                    ],
            ],
        26 =>
            [
                'CONST' =>
                    [
                        0 => 1,
                        1 => 5,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 5,
                    ],
                'NUMBER' =>
                    [
                        0 => 1,
                        1 => 5,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 1,
                        1 => 5,
                    ],
                '$' =>
                    [
                        0 => 1,
                        1 => 5,
                    ],
            ],
        27 =>
            [
                'JSX_TAG_END_OPEN' =>
                    [
                        0 => 0,
                        1 => 34,
                    ],
            ],
        28 =>
            [
                'JSX_TAG_END_OPEN' =>
                    [
                        0 => 1,
                        1 => 18,
                    ],
                'JSX_TEXT' =>
                    [
                        0 => 0,
                        1 => 30,
                    ],
                'BRACE_OPEN' =>
                    [
                        0 => 0,
                        1 => 31,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 0,
                        1 => 13,
                    ],
            ],
        29 =>
            [
                'JSX_TEXT' =>
                    [
                        0 => 1,
                        1 => 21,
                    ],
                'BRACE_OPEN' =>
                    [
                        0 => 1,
                        1 => 21,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 1,
                        1 => 21,
                    ],
                'JSX_TAG_END_OPEN' =>
                    [
                        0 => 1,
                        1 => 21,
                    ],
            ],
        30 =>
            [
                'JSX_TEXT' =>
                    [
                        0 => 1,
                        1 => 22,
                    ],
                'BRACE_OPEN' =>
                    [
                        0 => 1,
                        1 => 22,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 1,
                        1 => 22,
                    ],
                'JSX_TAG_END_OPEN' =>
                    [
                        0 => 1,
                        1 => 22,
                    ],
            ],
        31 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 11,
                    ],
                'NUMBER' =>
                    [
                        0 => 0,
                        1 => 12,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 0,
                        1 => 13,
                    ],
            ],
        32 =>
            [
                'JSX_ATTR_NAME' =>
                    [
                        0 => 1,
                        1 => 19,
                    ],
                'JSX_TAG_SELF_CLOSE' =>
                    [
                        0 => 1,
                        1 => 19,
                    ],
                'JSX_TAG_CLOSE' =>
                    [
                        0 => 1,
                        1 => 19,
                    ],
            ],
        33 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 11,
                    ],
                'NUMBER' =>
                    [
                        0 => 0,
                        1 => 12,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 0,
                        1 => 13,
                    ],
            ],
        34 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 38,
                    ],
            ],
        35 =>
            [
                'JSX_TAG_END_OPEN' =>
                    [
                        0 => 1,
                        1 => 17,
                    ],
            ],
        36 =>
            [
                'BRACE_CLOSE' =>
                    [
                        0 => 0,
                        1 => 39,
                    ],
            ],
        37 =>
            [
                'BRACE_CLOSE' =>
                    [
                        0 => 0,
                        1 => 40,
                    ],
            ],
        38 =>
            [
                'JSX_TAG_CLOSE' =>
                    [
                        0 => 0,
                        1 => 41,
                    ],
            ],
        39 =>
            [
                'JSX_TEXT' =>
                    [
                        0 => 1,
                        1 => 23,
                    ],
                'BRACE_OPEN' =>
                    [
                        0 => 1,
                        1 => 23,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 1,
                        1 => 23,
                    ],
                'JSX_TAG_END_OPEN' =>
                    [
                        0 => 1,
                        1 => 23,
                    ],
            ],
        40 =>
            [
                'JSX_ATTR_NAME' =>
                    [
                        0 => 1,
                        1 => 20,
                    ],
                'JSX_TAG_SELF_CLOSE' =>
                    [
                        0 => 1,
                        1 => 20,
                    ],
                'JSX_TAG_CLOSE' =>
                    [
                        0 => 1,
                        1 => 20,
                    ],
            ],
        41 =>
            [
                'CONST' =>
                    [
                        0 => 1,
                        1 => 14,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 14,
                    ],
                'NUMBER' =>
                    [
                        0 => 1,
                        1 => 14,
                    ],
                'JSX_TAG_OPEN' =>
                    [
                        0 => 1,
                        1 => 14,
                    ],
                '$' =>
                    [
                        0 => 1,
                        1 => 14,
                    ],
                'SEMICOLON' =>
                    [
                        0 => 1,
                        1 => 14,
                    ],
                'JSX_TEXT' =>
                    [
                        0 => 1,
                        1 => 14,
                    ],
                'BRACE_OPEN' =>
                    [
                        0 => 1,
                        1 => 14,
                    ],
                'JSX_TAG_END_OPEN' =>
                    [
                        0 => 1,
                        1 => 14,
                    ],
                'BRACE_CLOSE' =>
                    [
                        0 => 1,
                        1 => 14,
                    ],
            ],
    ];
    private const array GOTO = [
        0 =>
            [
                'statements' => 1,
                'statement' => 2,
                'constDeclaration' => 3,
                'expression' => 4,
                'jsxElement' => 6,
                'identifier' => 7,
                'number' => 8,
                'jsxSelfClosing' => 9,
                'jsxWithChildren' => 10,
            ],
        2 =>
            [
                'statements' => 14,
                'statement' => 2,
                'constDeclaration' => 3,
                'expression' => 4,
                'jsxElement' => 6,
                'identifier' => 7,
                'number' => 8,
                'jsxSelfClosing' => 9,
                'jsxWithChildren' => 10,
            ],
        16 =>
            [
                'jsxAttributes' => 18,
                'jsxAttribute' => 19,
            ],
        17 =>
            [
                'expression' => 21,
                'jsxElement' => 6,
                'identifier' => 7,
                'number' => 8,
                'jsxSelfClosing' => 9,
                'jsxWithChildren' => 10,
            ],
        19 =>
            [
                'jsxAttributes' => 24,
                'jsxAttribute' => 19,
            ],
        23 =>
            [
                'jsxChildren' => 27,
                'jsxChild' => 28,
                'jsxElement' => 29,
                'jsxSelfClosing' => 9,
                'jsxWithChildren' => 10,
            ],
        28 =>
            [
                'jsxChildren' => 35,
                'jsxChild' => 28,
                'jsxElement' => 29,
                'jsxSelfClosing' => 9,
                'jsxWithChildren' => 10,
            ],
        31 =>
            [
                'expression' => 36,
                'jsxElement' => 6,
                'identifier' => 7,
                'number' => 8,
                'jsxSelfClosing' => 9,
                'jsxWithChildren' => 10,
            ],
        33 =>
            [
                'expression' => 37,
                'jsxElement' => 6,
                'identifier' => 7,
                'number' => 8,
                'jsxSelfClosing' => 9,
                'jsxWithChildren' => 10,
            ],
        1 =>
            [
            ],
        3 =>
            [
            ],
        4 =>
            [
            ],
        5 =>
            [
            ],
        6 =>
            [
            ],
        7 =>
            [
            ],
        8 =>
            [
            ],
        9 =>
            [
            ],
        10 =>
            [
            ],
        11 =>
            [
            ],
        12 =>
            [
            ],
        13 =>
            [
            ],
        14 =>
            [
            ],
        15 =>
            [
            ],
        18 =>
            [
            ],
        20 =>
            [
            ],
        21 =>
            [
            ],
        22 =>
            [
            ],
        24 =>
            [
            ],
        25 =>
            [
            ],
        26 =>
            [
            ],
        27 =>
            [
            ],
        29 =>
            [
            ],
        30 =>
            [
            ],
        32 =>
            [
            ],
        34 =>
            [
            ],
        35 =>
            [
            ],
        36 =>
            [
            ],
        37 =>
            [
            ],
        38 =>
            [
            ],
        39 =>
            [
            ],
        40 =>
            [
            ],
        41 =>
            [
            ],
    ];
    private Parser $parser;

    public function __construct(Scanner $scanner)
    {
        $callbacks = [];
        $callbacks[0] = function (array $m) { return new Program($m[0]); };
        $callbacks[1] = function (array $m) { return [$m[0], ...$m[1]]; };
        $callbacks[2] = function (array $m) { return []; };
        $callbacks[3] = function (array $m) { return $m[0]; };
        $callbacks[4] = function (array $m) { return $m[0]; };
        $callbacks[5] = function (array $m) { return new ConstDeclaration($m[1], $m[3]); };
        $callbacks[6] = function (array $m) { return $m[0]; };
        $callbacks[7] = function (array $m) { return $m[0]; };
        $callbacks[8] = function (array $m) { return $m[0]; };
        $callbacks[9] = function (array $m) { return $m[0]; };
        $callbacks[10] = function (array $m) { return $m[0]; };
        $callbacks[11] = function (array $m) { return new Identifier($m[0]); };
        $callbacks[12] = function (array $m) { return new NumberLiteral($m[0]); };
        $callbacks[13] = function (array $m) { return new JsxElement($m[1], $m[2], []); };
        $callbacks[14] = function (array $m) {
            if ($m[1] !== $m[6]) {
                throw new \Exception("Mismatched tags: <$m[1]> and </$m[6]>");
            }
            return new JsxElement($m[1], $m[2], $m[4]);
        };
        $callbacks[15] = function (array $m) { return [$m[0], ...$m[1]]; };
        $callbacks[16] = function (array $m) { return []; };
        $callbacks[17] = function (array $m) { return [$m[0], ...$m[1]]; };
        $callbacks[18] = function (array $m) { return []; };
        $callbacks[19] = function (array $m) { return new JsxAttribute($m[0], $m[2]); };
        $callbacks[20] = function (array $m) { return new JsxAttribute($m[0], $m[3]); };
        $callbacks[21] = function (array $m) { return $m[0]; };
        $callbacks[22] = function (array $m) { return new TextNode($m[0]); };
        $callbacks[23] = function (array $m) { return new Interpolation($m[1]); };
        $this->parser = new Parser(self::ACTIONS, self::GOTO, $callbacks, self::RULES, $scanner);
    }

    public function parse(string $input): mixed
    {
        return $this->parser->parse($input);
    }
}
