<?php

declare(strict_types = 1);

namespace Resrap\Component\Grammar;

use Resrap\Component\Grammar\Ast\Directive;
use Resrap\Component\Grammar\Ast\GrammarDefinition;
use Resrap\Component\Grammar\Ast\RuleDefinition;
use Resrap\Component\Grammar\Ast\RuleToken;
use Resrap\Component\Grammar\Ast\UseStatement;
use Resrap\Component\Parser\Parser;
use Resrap\Component\Scanner\Scanner;

/**
 * This file was generated by the grammar compiler.
 * Do not edit it manually.
 */
final class GrammarFileParser
{
    private const array RULES = [
        0 =>
            [
                0 => 'grammar_file',
                1 =>
                    [
                        0 => 'directives',
                        1 => 'grammar_definitions',
                    ],
            ],
        1 =>
            [
                0 => 'directives',
                1 =>
                    [
                        0 => 'directive',
                        1 => 'directives',
                    ],
            ],
        2 =>
            [
                0 => 'directives',
                1 =>
                    [
                        0 => 'directive',
                    ],
            ],
        3 =>
            [
                0 => 'grammar_definitions',
                1 =>
                    [
                        0 => 'grammar_definition',
                        1 => 'grammar_definitions',
                    ],
            ],
        4 =>
            [
                0 => 'grammar_definitions',
                1 =>
                    [
                        0 => 'grammar_definition',
                    ],
            ],
        5 =>
            [
                0 => 'directive',
                1 =>
                    [
                        0 => 'NAMESPACE',
                        1 => 'qualified_identifier',
                        2 => 'SEMICOLON',
                    ],
            ],
        6 =>
            [
                0 => 'directive',
                1 =>
                    [
                        0 => 'DEFINE_CLASSNAME',
                        1 => 'IDENTIFIER',
                        2 => 'SEMICOLON',
                    ],
            ],
        7 =>
            [
                0 => 'directive',
                1 =>
                    [
                        0 => 'START',
                        1 => 'IDENTIFIER',
                        2 => 'SEMICOLON',
                    ],
            ],
        8 =>
            [
                0 => 'directive',
                1 =>
                    [
                        0 => 'USE',
                        1 => 'qualified_identifier',
                        2 => 'SEMICOLON',
                    ],
            ],
        9 =>
            [
                0 => 'directive',
                1 =>
                    [
                        0 => 'USE',
                        1 => 'qualified_identifier',
                        2 => 'AS',
                        3 => 'IDENTIFIER',
                        4 => 'SEMICOLON',
                    ],
            ],
        10 =>
            [
                0 => 'grammar_definition',
                1 =>
                    [
                        0 => 'IDENTIFIER',
                        1 => 'ASSIGN',
                        2 => 'rule_alternatives',
                        3 => 'SEMICOLON',
                    ],
            ],
        11 =>
            [
                0 => 'qualified_identifier',
                1 =>
                    [
                        0 => 'IDENTIFIER',
                    ],
            ],
        12 =>
            [
                0 => 'qualified_identifier',
                1 =>
                    [
                        0 => 'qualified_identifier',
                        1 => 'BACKSLASH',
                        2 => 'IDENTIFIER',
                    ],
            ],
        13 =>
            [
                0 => 'rule_alternatives',
                1 =>
                    [
                        0 => 'rule_production',
                        1 => 'PIPE',
                        2 => 'rule_alternatives',
                    ],
            ],
        14 =>
            [
                0 => 'rule_alternatives',
                1 =>
                    [
                        0 => 'rule_production',
                    ],
            ],
        15 =>
            [
                0 => 'rule_production',
                1 =>
                    [
                        0 => 'rule_tokens',
                        1 => 'CODE_BLOCK',
                    ],
            ],
        16 =>
            [
                0 => 'rule_production',
                1 =>
                    [
                        0 => 'CODE_BLOCK',
                    ],
            ],
        17 =>
            [
                0 => 'rule_tokens',
                1 =>
                    [
                        0 => 'rule_token',
                        1 => 'rule_tokens',
                    ],
            ],
        18 =>
            [
                0 => 'rule_tokens',
                1 =>
                    [
                        0 => 'rule_token',
                    ],
            ],
        19 =>
            [
                0 => 'rule_token',
                1 =>
                    [
                        0 => 'qualified_identifier',
                        1 => 'STATIC_ACCESS',
                        2 => 'IDENTIFIER',
                    ],
            ],
        20 =>
            [
                0 => 'rule_token',
                1 =>
                    [
                        0 => 'IDENTIFIER',
                    ],
            ],
        21 =>
            [
                0 => 'rule_token',
                1 =>
                    [
                        0 => 'STRING',
                    ],
            ],
        22 =>
            [
                0 => 'rule_token',
                1 =>
                    [
                        0 => 'CHAR',
                    ],
            ],
    ];
    private const array ACTIONS = [
        0 =>
            [
                'NAMESPACE' =>
                    [
                        0 => 0,
                        1 => 3,
                    ],
                'DEFINE_CLASSNAME' =>
                    [
                        0 => 0,
                        1 => 4,
                    ],
                'START' =>
                    [
                        0 => 0,
                        1 => 5,
                    ],
                'USE' =>
                    [
                        0 => 0,
                        1 => 6,
                    ],
            ],
        1 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 9,
                    ],
            ],
        2 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 2,
                    ],
                'NAMESPACE' =>
                    [
                        0 => 0,
                        1 => 3,
                    ],
                'DEFINE_CLASSNAME' =>
                    [
                        0 => 0,
                        1 => 4,
                    ],
                'START' =>
                    [
                        0 => 0,
                        1 => 5,
                    ],
                'USE' =>
                    [
                        0 => 0,
                        1 => 6,
                    ],
            ],
        3 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 12,
                    ],
            ],
        4 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 13,
                    ],
            ],
        5 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 14,
                    ],
            ],
        6 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 12,
                    ],
            ],
        7 =>
            [
                '$' =>
                    [
                        0 => 2,
                        1 => 0,
                    ],
            ],
        8 =>
            [
                '$' =>
                    [
                        0 => 1,
                        1 => 4,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 9,
                    ],
            ],
        9 =>
            [
                'ASSIGN' =>
                    [
                        0 => 0,
                        1 => 17,
                    ],
            ],
        10 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 1,
                    ],
            ],
        11 =>
            [
                'SEMICOLON' =>
                    [
                        0 => 0,
                        1 => 18,
                    ],
                'BACKSLASH' =>
                    [
                        0 => 0,
                        1 => 19,
                    ],
            ],
        12 =>
            [
                'SEMICOLON' =>
                    [
                        0 => 1,
                        1 => 11,
                    ],
                'AS' =>
                    [
                        0 => 1,
                        1 => 11,
                    ],
                'BACKSLASH' =>
                    [
                        0 => 1,
                        1 => 11,
                    ],
                'STATIC_ACCESS' =>
                    [
                        0 => 1,
                        1 => 11,
                    ],
            ],
        13 =>
            [
                'SEMICOLON' =>
                    [
                        0 => 0,
                        1 => 20,
                    ],
            ],
        14 =>
            [
                'SEMICOLON' =>
                    [
                        0 => 0,
                        1 => 21,
                    ],
            ],
        15 =>
            [
                'SEMICOLON' =>
                    [
                        0 => 0,
                        1 => 22,
                    ],
                'AS' =>
                    [
                        0 => 0,
                        1 => 23,
                    ],
                'BACKSLASH' =>
                    [
                        0 => 0,
                        1 => 19,
                    ],
            ],
        16 =>
            [
                '$' =>
                    [
                        0 => 1,
                        1 => 3,
                    ],
            ],
        17 =>
            [
                'CODE_BLOCK' =>
                    [
                        0 => 0,
                        1 => 27,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 30,
                    ],
                'STRING' =>
                    [
                        0 => 0,
                        1 => 31,
                    ],
                'CHAR' =>
                    [
                        0 => 0,
                        1 => 32,
                    ],
            ],
        18 =>
            [
                'NAMESPACE' =>
                    [
                        0 => 1,
                        1 => 5,
                    ],
                'DEFINE_CLASSNAME' =>
                    [
                        0 => 1,
                        1 => 5,
                    ],
                'START' =>
                    [
                        0 => 1,
                        1 => 5,
                    ],
                'USE' =>
                    [
                        0 => 1,
                        1 => 5,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 5,
                    ],
            ],
        19 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 33,
                    ],
            ],
        20 =>
            [
                'NAMESPACE' =>
                    [
                        0 => 1,
                        1 => 6,
                    ],
                'DEFINE_CLASSNAME' =>
                    [
                        0 => 1,
                        1 => 6,
                    ],
                'START' =>
                    [
                        0 => 1,
                        1 => 6,
                    ],
                'USE' =>
                    [
                        0 => 1,
                        1 => 6,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 6,
                    ],
            ],
        21 =>
            [
                'NAMESPACE' =>
                    [
                        0 => 1,
                        1 => 7,
                    ],
                'DEFINE_CLASSNAME' =>
                    [
                        0 => 1,
                        1 => 7,
                    ],
                'START' =>
                    [
                        0 => 1,
                        1 => 7,
                    ],
                'USE' =>
                    [
                        0 => 1,
                        1 => 7,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 7,
                    ],
            ],
        22 =>
            [
                'NAMESPACE' =>
                    [
                        0 => 1,
                        1 => 8,
                    ],
                'DEFINE_CLASSNAME' =>
                    [
                        0 => 1,
                        1 => 8,
                    ],
                'START' =>
                    [
                        0 => 1,
                        1 => 8,
                    ],
                'USE' =>
                    [
                        0 => 1,
                        1 => 8,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 8,
                    ],
            ],
        23 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 34,
                    ],
            ],
        24 =>
            [
                'SEMICOLON' =>
                    [
                        0 => 0,
                        1 => 35,
                    ],
            ],
        25 =>
            [
                'PIPE' =>
                    [
                        0 => 0,
                        1 => 36,
                    ],
                'SEMICOLON' =>
                    [
                        0 => 1,
                        1 => 14,
                    ],
            ],
        26 =>
            [
                'CODE_BLOCK' =>
                    [
                        0 => 0,
                        1 => 37,
                    ],
            ],
        27 =>
            [
                'PIPE' =>
                    [
                        0 => 1,
                        1 => 16,
                    ],
                'SEMICOLON' =>
                    [
                        0 => 1,
                        1 => 16,
                    ],
            ],
        28 =>
            [
                'CODE_BLOCK' =>
                    [
                        0 => 1,
                        1 => 18,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 30,
                    ],
                'STRING' =>
                    [
                        0 => 0,
                        1 => 31,
                    ],
                'CHAR' =>
                    [
                        0 => 0,
                        1 => 32,
                    ],
            ],
        29 =>
            [
                'STATIC_ACCESS' =>
                    [
                        0 => 0,
                        1 => 39,
                    ],
                'BACKSLASH' =>
                    [
                        0 => 0,
                        1 => 19,
                    ],
            ],
        30 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 20,
                    ],
                'STRING' =>
                    [
                        0 => 1,
                        1 => 20,
                    ],
                'CHAR' =>
                    [
                        0 => 1,
                        1 => 20,
                    ],
                'CODE_BLOCK' =>
                    [
                        0 => 1,
                        1 => 20,
                    ],
                'SEMICOLON' =>
                    [
                        0 => 1,
                        1 => 11,
                    ],
                'AS' =>
                    [
                        0 => 1,
                        1 => 11,
                    ],
                'BACKSLASH' =>
                    [
                        0 => 1,
                        1 => 11,
                    ],
                'STATIC_ACCESS' =>
                    [
                        0 => 1,
                        1 => 11,
                    ],
            ],
        31 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 21,
                    ],
                'STRING' =>
                    [
                        0 => 1,
                        1 => 21,
                    ],
                'CHAR' =>
                    [
                        0 => 1,
                        1 => 21,
                    ],
                'CODE_BLOCK' =>
                    [
                        0 => 1,
                        1 => 21,
                    ],
            ],
        32 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 22,
                    ],
                'STRING' =>
                    [
                        0 => 1,
                        1 => 22,
                    ],
                'CHAR' =>
                    [
                        0 => 1,
                        1 => 22,
                    ],
                'CODE_BLOCK' =>
                    [
                        0 => 1,
                        1 => 22,
                    ],
            ],
        33 =>
            [
                'SEMICOLON' =>
                    [
                        0 => 1,
                        1 => 12,
                    ],
                'AS' =>
                    [
                        0 => 1,
                        1 => 12,
                    ],
                'BACKSLASH' =>
                    [
                        0 => 1,
                        1 => 12,
                    ],
                'STATIC_ACCESS' =>
                    [
                        0 => 1,
                        1 => 12,
                    ],
            ],
        34 =>
            [
                'SEMICOLON' =>
                    [
                        0 => 0,
                        1 => 40,
                    ],
            ],
        35 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 10,
                    ],
                '$' =>
                    [
                        0 => 1,
                        1 => 10,
                    ],
            ],
        36 =>
            [
                'CODE_BLOCK' =>
                    [
                        0 => 0,
                        1 => 27,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 30,
                    ],
                'STRING' =>
                    [
                        0 => 0,
                        1 => 31,
                    ],
                'CHAR' =>
                    [
                        0 => 0,
                        1 => 32,
                    ],
            ],
        37 =>
            [
                'PIPE' =>
                    [
                        0 => 1,
                        1 => 15,
                    ],
                'SEMICOLON' =>
                    [
                        0 => 1,
                        1 => 15,
                    ],
            ],
        38 =>
            [
                'CODE_BLOCK' =>
                    [
                        0 => 1,
                        1 => 17,
                    ],
            ],
        39 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 0,
                        1 => 42,
                    ],
            ],
        40 =>
            [
                'NAMESPACE' =>
                    [
                        0 => 1,
                        1 => 9,
                    ],
                'DEFINE_CLASSNAME' =>
                    [
                        0 => 1,
                        1 => 9,
                    ],
                'START' =>
                    [
                        0 => 1,
                        1 => 9,
                    ],
                'USE' =>
                    [
                        0 => 1,
                        1 => 9,
                    ],
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 9,
                    ],
            ],
        41 =>
            [
                'SEMICOLON' =>
                    [
                        0 => 1,
                        1 => 13,
                    ],
            ],
        42 =>
            [
                'IDENTIFIER' =>
                    [
                        0 => 1,
                        1 => 19,
                    ],
                'STRING' =>
                    [
                        0 => 1,
                        1 => 19,
                    ],
                'CHAR' =>
                    [
                        0 => 1,
                        1 => 19,
                    ],
                'CODE_BLOCK' =>
                    [
                        0 => 1,
                        1 => 19,
                    ],
            ],
    ];
    private const array GOTO = [
        0 =>
            [
                'directives' => 1,
                'directive' => 2,
            ],
        1 =>
            [
                'grammar_definitions' => 7,
                'grammar_definition' => 8,
            ],
        2 =>
            [
                'directives' => 10,
                'directive' => 2,
            ],
        3 =>
            [
                'qualified_identifier' => 11,
            ],
        6 =>
            [
                'qualified_identifier' => 15,
            ],
        8 =>
            [
                'grammar_definitions' => 16,
                'grammar_definition' => 8,
            ],
        17 =>
            [
                'rule_alternatives' => 24,
                'rule_production' => 25,
                'rule_tokens' => 26,
                'rule_token' => 28,
                'qualified_identifier' => 29,
            ],
        28 =>
            [
                'rule_tokens' => 38,
                'rule_token' => 28,
                'qualified_identifier' => 29,
            ],
        36 =>
            [
                'rule_alternatives' => 41,
                'rule_production' => 25,
                'rule_tokens' => 26,
                'rule_token' => 28,
                'qualified_identifier' => 29,
            ],
        4 =>
            [
            ],
        5 =>
            [
            ],
        7 =>
            [
            ],
        9 =>
            [
            ],
        10 =>
            [
            ],
        11 =>
            [
            ],
        12 =>
            [
            ],
        13 =>
            [
            ],
        14 =>
            [
            ],
        15 =>
            [
            ],
        16 =>
            [
            ],
        18 =>
            [
            ],
        19 =>
            [
            ],
        20 =>
            [
            ],
        21 =>
            [
            ],
        22 =>
            [
            ],
        23 =>
            [
            ],
        24 =>
            [
            ],
        25 =>
            [
            ],
        26 =>
            [
            ],
        27 =>
            [
            ],
        29 =>
            [
            ],
        30 =>
            [
            ],
        31 =>
            [
            ],
        32 =>
            [
            ],
        33 =>
            [
            ],
        34 =>
            [
            ],
        35 =>
            [
            ],
        37 =>
            [
            ],
        38 =>
            [
            ],
        39 =>
            [
            ],
        40 =>
            [
            ],
        41 =>
            [
            ],
        42 =>
            [
            ],
    ];
    private Parser $parser;

    public function __construct(Scanner $scanner)
    {
        $callbacks = [];
        $callbacks[0] = function (array $m) { return new GrammarFileBuilder()->build($m[0], $m[1]); };
        $callbacks[1] = function (array $m) { return [$m[0], ...$m[1]]; };
        $callbacks[2] = function (array $m) { return [$m[0]]; };
        $callbacks[3] = function (array $m) { return [$m[0], ...$m[1]]; };
        $callbacks[4] = function (array $m) { return [$m[0]]; };
        $callbacks[5] = function (array $m) { return new Directive('namespace', $m[1]); };
        $callbacks[6] = function (array $m) { return new Directive('class', $m[1]); };
        $callbacks[7] = function (array $m) { return new Directive('start', $m[1]); };
        $callbacks[8] = function (array $m) { return new UseStatement($m[1]); };
        $callbacks[9] = function (array $m) { return new UseStatement($m[1], $m[3]); };
        $callbacks[10] = function (array $m) { return new GrammarDefinition($m[0], $m[2]); };
        $callbacks[11] = function (array $m) { return $m[0]; };
        $callbacks[12] = function (array $m) { return "{$m[0]}\\{$m[2]}"; };
        $callbacks[13] = function (array $m) { return [$m[0], ...$m[2]]; };
        $callbacks[14] = function (array $m) { return [$m[0]]; };
        $callbacks[15] = function (array $m) { return new RuleDefinition($m[0], trim($m[1])); };
        $callbacks[16] = function (array $m) { return new RuleDefinition([], trim($m[0])); };
        $callbacks[17] = function (array $m) { return [$m[0], ...$m[1]]; };
        $callbacks[18] = function (array $m) { return [$m[0]]; };
        $callbacks[19] = function (array $m) { return new RuleToken("{$m[0]}::{$m[2]}", RuleToken::TOK); };
        $callbacks[20] = function (array $m) { return new RuleToken($m[0], RuleToken::EXPR); };
        $callbacks[21] = function (array $m) { return new RuleToken($m[0], RuleToken::LITERAL); };
        $callbacks[22] = function (array $m) { return new RuleToken($m[0], RuleToken::LITERAL); };
        $this->parser = new Parser(self::ACTIONS, self::GOTO, $callbacks, self::RULES, $scanner);
    }

    public function parse(string $input): mixed
    {
        return $this->parser->parse($input);
    }
}
